name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove old files
      run: |
        go mod init main
        go build -v ./...
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_RUN_ID
    - name: Create Pull Request
      with:
        branch: prod
        title: ${{ github.event.inputs.notes }}
