name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ prod ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove old files
      run: |
        go mod init main
        go build -v ./...
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_RUN_ID
        echo ${{ GITHUB_RUN_NUMBER}}
        echo ${{ GITHUB_RUN_ID }}
