name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build Number Generator
  # You may pin to the exact commit or the version.
  # uses: einaregilsson/build-number@46decf22c413b48c8923e98b2b5836f8aaf7781e
      uses: einaregilsson/build-number@v3
      with:
    # GitHub Token to create and delete refs (GITHUB_TOKEN)
        token: ${{ secrets.GITHUB_TOKEN }}
    # Prefix for the build-number-<num> tag to make it unique if tracking multiple build numbers
     #   prefix: # optional
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
