name: PR

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print variables
        run: |
               echo $GITHUB_RUN_NUMBER
               echo $GITHUB_RUN_ID


      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.tag }}
          release_name: Release ${{ steps.tag_version.outputs.tag }}
          body: ${{ steps.tag_version.outputs.changelog }}