name: Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Print variables
      run: |
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_RUN_ID
        echo $GITHUB_JOB
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true



