name: Release to Prod

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: bump version from tag
        run: echo 'Hello DevTeam' > version.txt

      - uses: EndBug/add-and-commit@v9
        with:
          commit_message: Bump version to
