name: Release to Prod

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bump version from tag
        run: echo ${{ github.event.release.tag_name }} > version.txt

      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ github.event.release.tag_name }}
