name: Release to Prod

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Pulling ${{ github.ref }} into staging"
          destination_branch: "prod"
          source_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: Dez113
          pr_label: "auto-pr"