name: Release to Prod

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "prod"
          source_branch: "master"  
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: Dez113
          pr_label: "auto-pr"

